export const roomsData = [
    {
      id: 0,
      name: 'Livingroom',
      light: true,
      image: 'livingroom',
      temperature: 21,
    },
    {
      id: 1,
      name: 'Kitchen',
      light: true,
      image: 'kitchen',
      temperature: 21,
    },
    {
      id: 2,
      name: 'Master Bedroom',
      light: true,
      image: 'masterbedroom',
      temperature: 21,
    },
    {
      id: 3,
      name: 'Kids Bedroom',
      light: true,
      image: 'kidsbedroom',
      temperature: 21,
    },
    {
      id: 4,
      name: 'Master Bathroom',
      light: true,
      image: 'masterbathroom',
      temperature: 21,
    },
    {
      id: 5,
      name: 'Small Bathroom',
      light: true,
      image: 'smallbathroom',
      temperature: 21,
    },
    {
      id: 6,
      name: 'Hallway',
      light: true,
      image: 'hallway',
      temperature: 21,
    },
    
  ];

  export const temperatureData = {
    max: 30,
    min: 16,
  };
  
export const changesRecords = [
  {
    date: '2024-07-24',
    time: '19:14:00',
    utility: 'temperature',
    user: 'aleksa',
    room: 'Livingroom',
    change: '16',
  },
  {
    date: '2024-07-24',
    time: '19:14:00',
    utility: 'light',
    user: 'mark',
    room: 'Bathroom',
    change: 'off',
  },
  {
    date: '2024-07-25',
    time: '08:30:00',
    utility: 'temperature',
    user: 'john',
    room: 'Master Bedroom',
    change: '22',
  },
  {
    date: '2024-07-25',
    time: '09:45:00',
    utility: 'light',
    user: 'mary',
    room: 'Kitchen',
    change: 'on',
  },
  {
    date: '2024-07-25',
    time: '10:15:00',
    utility: 'temperature',
    user: 'anna',
    room: 'Kids Bedroom',
    change: '18',
  },
  {
    date: '2024-07-25',
    time: '12:20:00',
    utility: 'light',
    user: 'aleksa',
    room: 'Hallway',
    change: 'off',
  },
  {
    date: '2024-07-25',
    time: '13:00:00',
    utility: 'temperature',
    user: 'mark',
    room: 'Small Bathroom',
    change: '24',
  },
  {
    date: '2024-07-25',
    time: '14:45:00',
    utility: 'light',
    user: 'john',
    room: 'Livingroom',
    change: 'on',
  },
  {
    date: '2024-07-25',
    time: '15:30:00',
    utility: 'temperature',
    user: 'mary',
    room: 'Master Bathroom',
    change: '26',
  },
  {
    date: '2024-07-25',
    time: '16:00:00',
    utility: 'light',
    user: 'anna',
    room: 'Kitchen',
    change: 'off',
  },
  {
    date: '2024-07-25',
    time: '17:25:00',
    utility: 'temperature',
    user: 'aleksa',
    room: 'Livingroom',
    change: '20',
  },
  {
    date: '2024-07-25',
    time: '18:10:00',
    utility: 'light',
    user: 'mark',
    room: 'Master Bedroom',
    change: 'on',
  },
  {
    date: '2024-07-25',
    time: '19:40:00',
    utility: 'temperature',
    user: 'john',
    room: 'Hallway',
    change: '19',
  },
  {
    date: '2024-07-25',
    time: '20:55:00',
    utility: 'light',
    user: 'mary',
    room: 'Kids Bedroom',
    change: 'off',
  },
  {
    date: '2024-07-25',
    time: '21:15:00',
    utility: 'temperature',
    user: 'anna',
    room: 'Small Bathroom',
    change: '23',
  },
  {
    date: '2024-07-25',
    time: '22:05:00',
    utility: 'light',
    user: 'aleksa',
    room: 'Master Bathroom',
    change: 'on',
  },
  {
    date: '2024-07-26',
    time: '07:50:00',
    utility: 'temperature',
    user: 'mark',
    room: 'Livingroom',
    change: '21',
  },
  {
    date: '2024-07-26',
    time: '08:15:00',
    utility: 'light',
    user: 'john',
    room: 'Kitchen',
    change: 'off',
  },
  {
    date: '2024-07-26',
    time: '09:00:00',
    utility: 'temperature',
    user: 'mary',
    room: 'Master Bedroom',
    change: '25',
  },
  {
    date: '2024-07-26',
    time: '10:35:00',
    utility: 'light',
    user: 'anna',
    room: 'Hallway',
    change: 'on',
  },
  {
    date: '2024-07-26',
    time: '11:45:00',
    utility: 'temperature',
    user: 'aleksa',
    room: 'Small Bathroom',
    change: '28',
  },
  {
    date: '2024-07-26',
    time: '12:10:00',
    utility: 'light',
    user: 'mark',
    room: 'Kids Bedroom',
    change: 'off',
  },
  {
    date: '2024-07-26',
    time: '13:20:00',
    utility: 'temperature',
    user: 'john',
    room: 'Master Bathroom',
    change: '30',
  },
  {
    date: '2024-07-26',
    time: '14:40:00',
    utility: 'light',
    user: 'mary',
    room: 'Livingroom',
    change: 'on',
  },
  {
    date: '2024-07-26',
    time: '15:30:00',
    utility: 'temperature',
    user: 'anna',
    room: 'Kitchen',
    change: '27',
  },
  {
    date: '2024-07-26',
    time: '16:45:00',
    utility: 'light',
    user: 'aleksa',
    room: 'Master Bedroom',
    change: 'off',
  },
  {
    date: '2024-07-26',
    time: '17:25:00',
    utility: 'temperature',
    user: 'mark',
    room: 'Hallway',
    change: '18',
  },
  {
    date: '2024-07-26',
    time: '18:50:00',
    utility: 'light',
    user: 'john',
    room: 'Kids Bedroom',
    change: 'on',
  },
  {
    date: '2024-07-26',
    time: '19:30:00',
    utility: 'temperature',
    user: 'mary',
    room: 'Small Bathroom',
    change: '29',
  },
  {
    date: '2024-07-26',
    time: '20:15:00',
    utility: 'light',
    user: 'anna',
    room: 'Master Bathroom',
    change: 'off',
  },
];